### PR TITLE
Improve keyboard and screen-reader related accessibility

### PR DESCRIPTION
**Pull request by bgareth**
ISSUE: https://github.com/ruilisi/fortune-sheet/issues/573

This PR is intended to improve accessibility in order to address [WCAG 2.1](https://www.w3.org/TR/WCAG21/) accessibility standards as well as improve keyboard and screen-reader experience. 

Changes made:
- Toolbar
  - aria-label added to toolbar buttons (uses the same strings as the button tooltip)
  - Toolbar button images are decorative and now have `alt-text=""`
  - Added aria-label="Toolbar" to large toolbar group for section context (added "Toolbar" string reference and translations)
- Cell keyboard navigation
  - Added support for `Shit + Tab` to move cell focus left
- Added tab indices to all tags with an `onClick` attribute
  - `npx prettier --write ./packages` was needed to push commits for the large scope of the tab indices update

### CODE REVIEW

**Comment by sanchit3008** [comment]
i have reviewed the changes other than verifying tab index entries, which for some reason im unable to use. can you provide your intended user flow for these tab indices to be used?

**Comment by bgareth** [comment]
> i have reviewed the changes other than verifying tab index entries, which for some reason im unable to use. can you provide your intended user flow for these tab indices to be used?

Since there is a custom tab action, it will override the tab indices when tabbing. However, when using certain screen-readers, keyboard actions can change and there can be a separate set of controls to navigate between interact-able elements. This accounts for those cases as well as prevents testing software from flagging the issue as a requirement.

**Comment by sanchit3008** [comment]
understood, thanks. i need to learn more about accessibility softwares it seems. approving the pr.

**Review by sanchit3008 — APPROVED** [review]

**Comment by bgareth** [comment]
> understood, thanks. i need to learn more about accessibility softwares it seems. approving the pr.

Thank you @sanchit3008. Again, much appreciated.

**Pull request merged**
