### PR TITLE
fix: allowEdit not working

### LINKED ISSUE #341: allowEdit:false is not working on 0.16.0 version
when upgrade fortune-sheet from 0.15.3 to 0.16.0, allowEdit:false is not working anymore, 
although, allowEdit=false in setting, but the excel is still editable, can change/delete the value on excel
any workaround solution to make excel readonly?

### PR DESCRIPTION
**Pull request by shuanhukexuejia**
* fix #341

### CODE REVIEW

**Comment by gazedreamily** [comment]
LGTM

**Comment by Qaplagzy** [comment]
LGTM

**Comment by Bryanlhx** [comment]
may I know when you will release a new version to cover this change?

**Comment by shuanhukexuejia** [comment]
> 

@Bryanlhx 0.16.1 has been released

**Pull request merged**
