### PR TITLE
Fix: Highlight last cell on range movement

### LINKED ISSUE #459: Range Highlight selection movement bug
**Describe the bug**
When a range is selected by say pressing shift + right arrow and the origin cell goes beyond the visible screen - and then the user presses shift + left arrow then the screen jumps to the origin cell instead of keeping the last cell on the screen. This is a deviation from excel/google sheets.

**To Reproduce**
1. Click on a cell and keep pressing shift + right arrow until starting cell is not visible anymore
2. Now press shift + left arrow 
3. Notice that the screen jumps to starting cell instead of showing the last cell

**Expected behavior**
Screen should stay focussed on the end of range and not the start.

Fortunesheet -

https://github.com/ruilisi/fortune-sheet/assets/22197708/7a6262c0-8565-4605-84fe-91033f796de0

Google Sheets -

https://github.com/ruilisi/fortune-sheet/assets/22197708/c59803c0-5b38-478e-9676-0e8fe37e2ae6

### PR DESCRIPTION
**Pull request by sanchit3008**
Resolves #459 

Keep screen focussed on the last cell while moving highlighted ranges as is the case with excel/gsheets.

### CODE REVIEW

**Review by zyc9012 — COMMENTED** [review]
Thanks @sanchit3008 for the fix. However the algorithm seems complex. And `scrollToHighlightCell` shouldn't do things other than scroll according to `r` and `c`.

I came up with a different impl. Would you check if that works expectedly?

```diff
diff --git a/packages/core/src/modules/selection.ts b/packages/core/src/modules/selection.ts
index 792c277..a6990c1 100644
--- a/packages/core/src/modules/selection.ts
+++ b/packages/core/src/modules/selection.ts
@@ -39,30 +39,34 @@ export function scrollToHighlightCell(ctx: Context, r: number, c: number) {
   if (!sheet) return;
 
   const frozen = sheet?.frozen;
-  const row_focus = sheet?.frozen?.range?.row_focus || 0;
-  const column_focus = sheet?.frozen?.range?.column_focus || 0;
 
-  const freezeH = frozen && r > row_focus ? ctx.visibledatarow[row_focus] : 0;
-  const freezeW =
-    frozen && c > column_focus ? ctx.visibledatacolumn[column_focus] : 0;
-
-  const row = ctx.visibledatarow[r];
-  const row_pre = r - 1 === -1 ? 0 : ctx.visibledatarow[r - 1];
-  const col = ctx.visibledatacolumn[c];
-  const col_pre = c - 1 === -1 ? 0 : ctx.visibledatacolumn[c - 1];
-
-  if (col - scrollLeft - winW + 20 > 0) {
-    ctx.scrollLeft = col - winW + 20;
-  } else if (col_pre - scrollLeft - freezeW < 0) {
-    const scrollAmount = Math.max(20, freezeW);
-    ctx.scrollLeft = col_pre - scrollAmount;
+  if (r >= 0) {
+    const row_focus = sheet?.frozen?.range?.row_focus || 0;
+    const freezeH = frozen && r > row_focus ? ctx.visibledatarow[row_focus] : 0;
+    const row = ctx.visibledatarow[r];
+    const row_pre = r - 1 === -1 ? 0 : ctx.visibledatarow[r - 1];
+
+    if (row - scrollTop - winH + 20 > 0) {
+      ctx.scrollTop = row - winH + 20;
+    } else if (row_pre - scrollTop - freezeH < 0) {
+      const scrollAmount = Math.max(20, freezeH);
+      ctx.scrollTop = row_pre - scrollAmount;
+    }
   }
 
-  if (row - scrollTop - winH + 20 > 0) {
-    ctx.scrollTop = row - winH + 20;
-  } else if (row_pre - scrollTop - freezeH < 0) {
-    const scrollAmount = Math.max(20, freezeH);
-    ctx.scrollTop = row_pre - scrollAmount;
+  if (c >= 0) {
+    const column_focus = sheet?.frozen?.range?.column_focus || 0;
+    const freezeW =
+      frozen && c > column_focus ? ctx.visibledatacolumn[column_focus] : 0;
+    const col = ctx.visibledatacolumn[c];
+    const col_pre = c - 1 === -1 ? 0 : ctx.visibledatacolumn[c - 1];
+
+    if (col - scrollLeft - winW + 20 > 0) {
+      ctx.scrollLeft = col - winW + 20;
+    } else if (col_pre - scrollLeft - freezeW < 0) {
+      const scrollAmount = Math.max(20, freezeW);
+      ctx.scrollLeft = col_pre - scrollAmount;
+    }
   }
 }
 
@@ -1278,10 +1282,15 @@ export function moveHighlightRange(
     last.row = rowseleted;
     last.column = columnseleted;
     normalizeSelection(ctx, ctx.luckysheet_select_save);
-    if (index === -1) {
-      scrollToHighlightCell(ctx, last.row[0], last.column[0]);
+
+    if (postion === "down") {
+      const rowToScroll =
+        last.row_focus === last.row[0] ? last.row[1] : last.row[0];
+      scrollToHighlightCell(ctx, rowToScroll, -1);
     } else {
-      scrollToHighlightCell(ctx, last.row[1], last.column[1]);
+      const columnToScroll =
+        last.column_focus === last.column[0] ? last.column[1] : last.column[0];
+      scrollToHighlightCell(ctx, -1, columnToScroll);
     }
   } else if (type === "rangeOfFormula") {
     const last = ctx.formulaCache.func_selectedrange;
```

**Comment by sanchit3008** [comment]
Thanks for going thru this in such detail, let me confirm and get back to you on this @zyc9012

**Comment by sanchit3008** [comment]
@zyc9012 the changes suggested by you are breaking the horizontal scroll functionality.


https://github.com/ruilisi/fortune-sheet/assets/22197708/b2ba2401-9572-4c38-81c9-b13c7bcd0749

**Comment by zyc9012** [comment]
@sanchit3008 What's weird, it works on my end. Are you using shift+arrowkey to expand the selection?


https://github.com/ruilisi/fortune-sheet/assets/3034310/d055cdbd-e26c-4a82-ba29-2be16d6f5f3a

**Comment by sanchit3008** [comment]
Weird, yes I am using shift arrow. Is it possible for you top create a branch with these changes for easier testing across systems? @zyc9012

**Comment by zyc9012** [comment]
@sanchit3008 fix-arrowkey-range-movement

**Comment by zyc9012** [comment]
@sanchit3008 Pushed to master.

**Comment by sanchit3008** [comment]
Thanks @zyc9012, marking this PR as closed.

**Pull request closed without merging**
