### PR TITLE
fix: Display issue with value filtering

### PR DESCRIPTION
**Pull request by ZhengIce**
fix :
   * When using value filtering in the filter, the 'unChecked' state of unselected values is not updated

### CODE REVIEW

**Comment by zyc9012** [comment]
How to reproduce?

**Comment by ZhengIce** [comment]
QQ图片20230625192225

**Review by sanchit3008 — APPROVED** [review]

**Review by zyc9012 — CHANGES_REQUESTED** [review]
Let's delete `contextRef` and use `context` directly

**Comment by ZhengIce** [comment]
@zyc9012 This piece of code does not need to be triggered continuously

**Comment by ZhengIce** [comment]
@zyc9012 Directly using `context` will affect each other during collaboration

**Review by zyc9012 — APPROVED** [review]
Thanks @ZhengIce 👍

**Pull request merged**
