### PR TITLE
feat:Config number rows to add on Button click

### PR DESCRIPTION
**Pull request by jikoczl**
This PR belongs to @gudipudipradeep. But he met some problems with git. I help him to give this PR.

### CODE REVIEW

**Comment by gudipudipradeep** [comment]
Perfect.. Thanks @jikoczl 
something very bad with my pull request after lot of operations.

**Comment by jikoczl** [comment]
This PR resolves #134 by @gudipudipradeep .

**Comment by Qaplagzy** [comment]
LGTM

**Comment by shuanhukexuejia** [comment]
LGTM

**Pull request merged**
