### PR TITLE
fix: handle refresh and clipboard for paste

### LINKED ISSUE #512: Pasting a cell value does not update formulae
**Describe the bug**

**To Reproduce**
1. Define a formula based on some cell
2. Paste value into the cell
3. See error

**Expected behavior**
Formulae should get updated.

**Screenshots**

https://github.com/ruilisi/fortune-sheet/assets/22197708/a96f93f1-aea0-4141-90d4-c2d265a20a6d

### LINKED ISSUE #518: Paste from right click context menu does not work with non cell data
**Describe the bug**
ctrl/cmd+v works fine, but right click -> paste either doesn't paste anything, or just pastes the last copied cell value (and not what is actually on the clipboard).

**To Reproduce**
1. Copy some text from a non sheet environment
2. Right click on any cell -> paste
3. Nothing gets pasted

**Expected behavior**
Copied text should be pasted

**Screenshots**

https://github.com/ruilisi/fortune-sheet/assets/22197708/f31fb969-eb8a-4b65-a1af-17cfb0574879

### PR DESCRIPTION
**Pull request by sanchit3008**
Closes #512 
Closes #518 

1. Refresh the grid on data being pasted to update formulae
2. Read data from clipboard on right click context menu paste

https://github.com/ruilisi/fortune-sheet/assets/22197708/3b8ecf3c-a44b-4890-89ae-ce7dfdf8ee1c

### CODE REVIEW

**Comment by sanchit3008** [comment]
@zyc9012 can you pls review then 4-5 open PRs? thanks.

**Comment by sanchit3008** [comment]
let me know in case any clarification is needed @zyc9012 , need these 3-4 fixes for a case

**Comment by sanchit3008** [comment]
@zyc9012 please help with this, im quite dependent on this fix getting released

**Comment by zyc9012** [comment]
Thanks for these fixes @sanchit3008. I'll double-check this weekend. But feel free to release on your own.

**Pull request merged**
