### PR TITLE
Implemented partial protected example to storybook.

### PR DESCRIPTION
**Pull request by juanparati**
I implemented an additional example that uses colReadOnly and rowReadOnly instead of loc.

### CODE REVIEW

**Review by zyc9012 — COMMENTED** [review]
@juanparati is adding `numfmt` related to this PR?

**Comment by juanparati** [comment]
@zyc9012 : I added numfmt some days after to pull request the storybook example. I thought that this PR was already merged :(

From now I will create different branches in my repo in order to avoid this problem.

**Comment by juanparati** [comment]
@zyc9012 : I reverted the last commit. I will push the numfmt in a different pull request.

**Comment by zyc9012** [comment]
Thanks @juanparati 👍

**Pull request merged**
