### PR TITLE
undefined check for flowdata[r]

### LINKED ISSUE #452: Undefined check bug
**Describe the bug**
`rowHasMerged` function in `selection.ts` needs an additional check to avoid the sheet breaking due to a reference error. Specifically - `if (_.isNil(flowData)) return false;` should be changed to `if (_.isNil(flowData) || _.isNil(flowData[r])) return false;` to handle the cases where both starting cell and destination cell is part of a merged field. Otherwise the entire sheet breaks.

**To Reproduce**
Use the following data -

```
const data = {
  name: "Empty",
  status: 1,
  config: {
    merge: {
      "0_0": {
        r: 0,
        c: 0,
        rs: 1,
        cs: 6,
      },
      "1_0": {
        r: 1,
        c: 0,
        rs: 1,
        cs: 2,
      },
      "1_2": {
        r: 1,
        c: 2,
        rs: 1,
        cs: 2,
      },
      "1_4": {
        r: 1,
        c: 4,
        rs: 1,
        cs: 2,
      },
    },
  },
  celldata: [
    { r: 0, c: 0, v: { mc: { r: 0, c: 0, rs: 1, cs: 6 } } },
    { r: 0, c: 1, v: { mc: { r: 0, c: 0 } } },
    { r: 0, c: 2, v: { mc: { r: 0, c: 0 } } },
    { r: 0, c: 3, v: { mc: { r: 0, c: 0 } } },
    { r: 0, c: 4, v: { mc: { r: 0, c: 0 } } },
    { r: 0, c: 5, v: { mc: { r: 0, c: 0 } } },
    { r: 0, c: 6, v: { mc: { r: 0, c: 0 } } },

    { r: 1, c: 0, v: { mc: { r: 1, c: 0, rs: 1, cs: 2 } } },
    { r: 1, c: 1, v: { mc: { r: 1, c: 0 } } },
  ],
};

export default data;
```

Then goto storybook, click on b1 and press shift+up arrow.

**Expected behavior**
Sheet shouldn't break.

https://github.com/ruilisi/fortune-sheet/assets/22197708/13dfafec-3892-4683-aadd-108c957757dc

### PR DESCRIPTION
**Pull request by sanchit3008**
Resolves #452 

Demo after making these changes (error demo is in the issue) - 

https://github.com/ruilisi/fortune-sheet/assets/22197708/7cc3cc62-2004-45fe-87ba-eae94ff0fbed

Please merge on priority if possible @zyc9012 @gazedreamily

### CODE REVIEW

**Comment by sanchit3008** [comment]
Any estimate on when this can be reviewed @zyc9012 @gazedreamily @ZhengIce ? Also I think we can release a new version now as it has been quite some time.

**Comment by sanchit3008** [comment]
Yes @zyc9012 your suggestion works. This line is erroneous in cases where are selecting a merged cell while being inside a merged cell so isn't actually a ts issue.

**Comment by sanchit3008** [comment]
Have committed your suggestion.

**Review by zyc9012 — APPROVED** [review]

**Comment by zyc9012** [comment]
@Qaplagzy Let's release a new version.

**Comment by sanchit3008** [comment]
Thank you @zyc9012 for accommodating.

**Comment by sanchit3008** [comment]
@Qaplagzy pls let me know when you're able to release

**Comment by zyc9012** [comment]
@sanchit3008 Released

**Pull request merged**
